# Generated by Django 3.2.7 on 2021-10-10 16:37

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211010_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[students.validators.no_elon_validator, students.validators.prohibited_domains]),
        ),
    ]
