# Generated by Django 3.2.7 on 2021-11-14 21:33

import django.core.validators
from django.db import migrations, models
import students.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=120, null=True, validators=[students.validators.no_elon_validator, students.validators.prohibited_domains])),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\d{10,14}')])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ManyToManyField(related_name='teacher_course', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
