# Generated by Django 3.2.7 on 2021-10-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='comments',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses_headed',
        ),
    ]
