# Generated by Django 3.2.7 on 2021-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211009_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='not stated', max_length=120),
        ),
    ]
