# Generated by Django 3.2.7 on 2021-10-03 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80)),
                ('st_number', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.date(2021, 10, 3), null=True)),
                ('course', models.CharField(max_length=40)),
            ],
        ),
    ]
