# Generated by Django 3.2.7 on 2021-10-10 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211009_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 10, 10), null=True),
        ),
    ]
